# Generated by Django 5.2 on 2025-04-15 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('int_pk_cust', models.AutoField(primary_key=True, serialize=False)),
                ('str_cust_name', models.CharField(max_length=150)),
                ('str_cust_email', models.EmailField(max_length=254)),
                ('str_cust_adress', models.CharField(max_length=255)),
                ('dt_cust_dt_regist', models.DateTimeField()),
                ('dt_cust_created_at', models.DateTimeField(auto_now=True)),
                ('dt_cust_updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('int_pk_pro', models.AutoField(primary_key=True, serialize=False)),
                ('str_pro_name', models.CharField(max_length=255)),
                ('dbl_pro_price', models.FloatField()),
                ('int_pro_stock', models.IntegerField()),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('int_pk_order', models.AutoField(primary_key=True, serialize=False)),
                ('dt_order_dt_regist', models.DateTimeField()),
                ('str_order_status', models.CharField(max_length=100)),
                ('int_customer_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_pro_qty', models.IntegerField()),
                ('dbl_inutary_price', models.FloatField()),
                ('int_order_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
                ('int_pro_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
    ]
