# Generated by Django 5.2 on 2025-04-15 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_orderdetails_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='int_pk_cust',
            new_name='int_cust_pk',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='int_pk_order',
            new_name='int_order_pk',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='int_pk_pro',
            new_name='int_pro_pk',
        ),
    ]
